'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("USB_Raptor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Backdoor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backdoor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Check2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Key2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Magic_Wand_Noise() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Magic_Wand_Noise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Puzzle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Puzzle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Raptor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Raptor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Blue_Claws() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Blue_Claws", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Blue_Claws1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Blue_Claws1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Blue_Tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Blue_Tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Blue_Tray1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Blue_Tray1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_DarkBlue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_DarkBlue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Gray_Tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Gray_Tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Gray_Tray1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Gray_Tray1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Green() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Green", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Green_Claws() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Green_Claws", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Green_Tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Green_Tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_GreenBlue_Claws() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_GreenBlue_Claws", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_GreenBlue_Claws1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_GreenBlue_Claws1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Orange_Claws() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Orange_Claws", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Purple_Claws() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Purple_Claws", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Purple_Tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Purple_Tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Purrple() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Purrple", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Red_Tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Red_Tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Yellow() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Yellow", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws_New_Yellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws_New_Yellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClaws2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClaws2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorClawsRED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorClawsRED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorGREEN() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorGREEN", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorPURPLE() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorPURPLE", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RaptorRED() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorRED", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorText_About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorText-About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorText_About_Highlighted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorText-About_Highlighted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorText_Horizontal_200_DarkGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorText-Horizontal_200_DarkGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RaptorText_Vertical_200_LightGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RaptorText-Vertical_200_LightGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
